// app/routes/index.tsx
import {
  ActionFunction,
  Form,
  HeadersFunction,
  Link,
  useActionData,
  useTransition,
} from "remix";
import { createUrl } from "~/data/urlService";
import copyToClipboard from "~/lib/copyToClipboard";

export const headers: HeadersFunction = () => {
  return {
    "Cache-Control": "s-maxage=300",
  };
};

export const action: ActionFunction = async ({ request }) => {
  try {
    const formData = await request.formData();
    const hashedUrl = await createUrl(formData.get("url") as string);
    const proto = process.env.NODE_ENV === "production" ? "https" : "http";
    const host = request.headers.get("host");

    return {
      result: `${proto}://${host}/u/${hashedUrl}`,
    };
  } catch (error) {
    return { error: (error as any).message };
  }
};

export default function Index() {
  const { result, error } = useActionData() || {};
  const { state } = useTransition();
  const isLoading = state === "submitting" || state === "loading";

  function handleCopy() {
    copyToClipboard(result);
  }

  return (
    <>
      <main>
        <h1 className="text-6xl font-bold mb-12">urls.wtf</h1>

        <div className="space-y-1">
          <p>minimalistic url shortener.</p>
          <p>no tracking.</p>
          <p>no ads.</p>
        </div>

        <Form
          className="text-bluePlaza flex items-center space-x-6 mt-12"
          method="post"
        >
          <input
            name="url"
            placeholder="Type in your url..."
            aria-label="Enter an URL to shorten"
            className="p-2 w-full rounded"
          />

          <button className="bg-white p-2 rounded h-full" type="submit">
            Go!
          </button>
        </Form>

        <div className="mt-6">
          <div className="h-8">
            {isLoading && <p>loading</p>}

            {!isLoading && (
              <>
                {result && (
                  <div className="flex items-center space-x-2">
                    <a
                      className="underline"
                      href={result}
                      target="_blank"
                      rel="noopener noreferer"
                    >
                      {result}
                    </a>

                    <button
                      className="bg-white text-bluePlaza px-2 rounded h-6"
                      onClick={handleCopy}
                    >
                      copy
                    </button>
                  </div>
                )}

                {error && <p>{error}</p>}
              </>
            )}
          </div>
        </div>
      </main>

      <footer className="mt-24">
        <a
          className="block underline mt-2"
          href="https://github.com/jfranciscosousa/urls.wtf"
        >
          View Github
        </a>

        <Link className="block underline mt-2" to="/terms">
          Terms of Service
        </Link>
      </footer>
    </>
  );
}

// src/routes/+page.svelte
<script lang="ts">
  import { applyAction, enhance } from "$app/forms";
  import copyToClipboard from "$lib/copyToClipboard";

  let loading = $state(false);
  let { form } = $props();

  function handleCopy() {
    if (form?.result) copyToClipboard(form?.result);
  }
</script>

<main>
  <h1 class="text-6xl font-bold mb-12">urls.wtf</h1>

  <div class="space-y-1">
    <p>minimalistic url shortener.</p>
    <p>no tracking.</p>
    <p>no ads.</p>
  </div>

  <form
    class="text-bluePlaza flex items-center space-x-6 mt-12"
    method="POST"
    use:enhance={() => {
      loading = true;

      return async ({ result }) => {
        await applyAction(result);
        loading = false;
      };
    }}
  >
    <!-- svelte-ignore a11y_autofocus -->
    <input
      name="url"
      placeholder="Type in your url..."
      aria-label="Enter an URL to shorten"
      class="p-2 w-full rounded"
      autofocus
    />

    <button class="bg-white p-2 rounded h-full" type="submit"> Go! </button>
  </form>

  <div class="mt-6">
    <div class="h-8">
      {#if loading}
        <p>loading</p>
      {:else if form?.result}
        <div class="flex items-center space-x-2">
          <a class="underline" href={form?.result} target="_blank" rel="noopener noreferrer">
            {form?.result}
          </a>

          <button class="bg-white text-bluePlaza px-2 rounded h-6" onclick={handleCopy}>
            copy
          </button>
        </div>
      {:else if form?.error}
        <p>{form?.error}</p>
      {/if}
    </div>
  </div>
</main>

<footer class="mt-24">
  <a class="block underline mt-2" href="https://github.com/jfranciscosousa/urls.wtf">
    View Github
  </a>

  <a class="block underline mt-2" href="/terms">Terms of Service</a>
</footer>
